services:
  - type: web           # Free-tier web service on Render
    name: campus-taxi-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/serviceAccountKey.json
      - key: SERVICE_ACCOUNT_JSON
        sync: false # Used for sensitive data (Secret)
